---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  kubeProxyMode: "ipvs"
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
nodes:
  - role: control-plane
    image: kindest/node:v1.24.2
    extraMounts:
      - hostPath: /vagrant/bin
        containerPath: /opt/cni/bash/bin
      - hostPath: /opt/containernetworking/plugins
        containerPath: /opt/cni/plugins/bin
