---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check Demos
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'

jobs:
  check-demo:
    strategy:
      matrix:
        demo: [pause, ipvs, flannel]
    runs-on: ubuntu-20.04
    env:
      GO111MODULE: "on"
      DEMO_TYPE: ${{ matrix.demo }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup common folder
        run: mkdir -p /opt/common && cp ./common/* /opt/common
      - name: Install dependencies
        run: cd "$DEMO_TYPE"; ./install.sh
      - name: Configure services
        run: cd "$DEMO_TYPE"; ./configure.sh
      - name: Run demo
        run: cd "$DEMO_TYPE"; ./demo.sh
